#' Create Hex Stickers for R Packages
#'
#' @title Create Hex Stickers for R Packages
#' @description Generates hexadecimal stickers for R packages using a provided
#'    description and package name. The stickers are generated by the OpenAI API.
#'    This is an experimental function.
#' @param description A string. This is the description of the R package for which the stickers will be generated.
#' @param package_name A string. This is the name of the R package for which the stickers will be generated.
#' @param n An integer. This is the number of stickers to generate. The default value is 3.
#' @importFrom assertthat assert_that
#' @importFrom httr POST add_headers content
#' @importFrom jsonlite toJSON
#' @importFrom purrr map
#' @importFrom hexSticker sticker
#' @return A list of EBImage objects. These are the hexadecimal stickers generated for the R package.
#' @export createHEX_with_generateImage4R
#' @author Satoshi Kume
#'
#' @examples
#' \dontrun{
#' # Define a description for the R package
#' description = "chatAI4R provides a seamless interface for integrating OpenAI and other APIs into R."
#' package_name = "chatAI4R"
#'
#' # Generate hex stickers
#' res <- createHEX_with_generateImage4R(description, package_name)
#'
#' # Display the stickers
#' Display(res)
#' }

createHEX_with_generateImage4R <- function(description,
                                           package_name,
                                           n = 1){
  # Verify the types of the input parameters
  assertthat::assert_that(assertthat::is.string(description))
  assertthat::assert_that(assertthat::is.string(package_name))
  assertthat::assert_that(assertthat::is.count(n))

  # Create the prompt
  pr <- paste0('Generate one hexadecimal sticker with background transparent as called "hex sticker" for the R package at the center of the output image using the following description: ',
               description)

  # Generate the image
  res <-  generateDalleImage4R(content = pr,
                          model = "dall-e-3",
                          n = 1,
                          size = "1024x1024",
                          response_format = "url",
                          Output_image = FALSE,
                          SaveImg = FALSE)



  # Create the hex stickers
  img <- list()
  if( model == "dall-e-3" ){
  for(k in seq_len(n)){
    suppressMessages(
    img[[1]][k] <- res[2]
    img[[2]][k] <-  hexSticker::sticker(res[2],
                                     package = package_name,
                                     p_y = 1.5, p_size=12,
                                     s_x=1, s_y=.8, s_width=.5)
    )
  }else{
  for(k in seq_len(n)){
    suppressMessages(
    img[[k]] <-  hexSticker::sticker(res[k],
                                     package = package_name,
                                     p_y = 1.5, p_size=12,
                                     s_x=1, s_y=.8, s_width=.5)
    )}
  }

  # Return the result
  return(img)
}
